name: arya-ai-app

services:
  - name: arya-backend
    git:
      branch: main
    instance_types:
      - free
    ports:
      - port: 8000
        protocol: http
    env:
      - key: PORT
        value: "8000"
    health_check:
      http:
        path: /health
    build:
      type: dockerfile
      dockerfile: Dockerfile
