services:
  - type: web
    name: proagent-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1 --timeout-keep-alive 30
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: false
      - key: KEEP_ALIVE
        value: true
